[project]
name = "nbdev-play"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "jupyterlab>=4.4.5",
    "jupyterlab-quarto>=0.3.5",
    "nbdev>=2.4.5",
]
